-- User
hl.bind("CTRL + SUPER + Slash", hl.dsp.exec_cmd("xdg-open ~/.config/illogical-impulse/config.json"), { description = "Edit shell config" })
hl.bind("CTRL + SUPER + ALT + Slash", hl.dsp.exec_cmd("xdg-open ~/.config/hypr/custom/keybinds.lua"), { description = "Edit extra keybinds" })

-- Unbind default keybinds to replace with custom behavior
hl.unbind("SUPER + H")
hl.unbind("SUPER + L")
hl.unbind("SUPER + K")
hl.unbind("SUPER + J")
hl.unbind("SUPER + Left")
hl.unbind("SUPER + Right")
hl.unbind("SUPER + Up")
hl.unbind("SUPER + Down")
hl.unbind("SUPER + SHIFT + Left")
hl.unbind("SUPER + SHIFT + Right")
hl.unbind("SUPER + SHIFT + Up")
hl.unbind("SUPER + SHIFT + Down")
hl.unbind("SUPER + SHIFT + L")
hl.unbind("SUPER + ALT + code:10")
hl.unbind("SUPER + ALT + code:11")
hl.unbind("SUPER + ALT + code:12")
hl.unbind("SUPER + ALT + code:13")
hl.unbind("SUPER + ALT + code:14")
hl.unbind("SUPER + ALT + code:15")
hl.unbind("SUPER + ALT + code:16")
hl.unbind("SUPER + ALT + code:17")
hl.unbind("SUPER + ALT + code:18")
hl.unbind("SUPER + ALT + code:19")
hl.unbind("SUPER + ALT + code:87")
hl.unbind("SUPER + ALT + code:88")
hl.unbind("SUPER + ALT + code:89")
hl.unbind("SUPER + ALT + code:83")
hl.unbind("SUPER + ALT + code:84")
hl.unbind("SUPER + ALT + code:85")
hl.unbind("SUPER + ALT + code:79")
hl.unbind("SUPER + ALT + code:80")
hl.unbind("SUPER + ALT + code:81")
hl.unbind("SUPER + ALT + code:90")
hl.unbind("SUPER + SHIFT + S")
hl.unbind("CTRL + ALT + T")
hl.unbind("SUPER + B")
hl.unbind("SUPER + O")

-- Session
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("loginctl lock-session"), { description = "Lock" })

-- Window: focus
hl.bind("SUPER + H", hl.dsp.focus({ direction = "l" }), { hidden = true })
hl.bind("SUPER + L", hl.dsp.focus({ direction = "r" }), { hidden = true })
hl.bind("SUPER + K", hl.dsp.focus({ direction = "u" }), { hidden = true })
hl.bind("SUPER + J", hl.dsp.focus({ direction = "d" }), { hidden = true })

-- Window: move
hl.bind("SUPER + Left", hl.dsp.window.move({ direction = "l" }), { hidden = true })
hl.bind("SUPER + Right", hl.dsp.window.move({ direction = "r" }), { hidden = true })
hl.bind("SUPER + Up", hl.dsp.window.move({ direction = "u" }), { hidden = true })
hl.bind("SUPER + Down", hl.dsp.window.move({ direction = "d" }), { hidden = true })

-- Window: resize
hl.bind("SUPER + SHIFT + Right", hl.dsp.window.resize({ x = 20, y = 0 }), { hidden = true })
hl.bind("SUPER + SHIFT + Left", hl.dsp.window.resize({ x = -20, y = 0 }), { hidden = true })
hl.bind("SUPER + SHIFT + Up", hl.dsp.window.resize({ x = 0, y = -20 }), { hidden = true })
hl.bind("SUPER + SHIFT + Down", hl.dsp.window.resize({ x = 0, y = 20 }), { hidden = true })

-- Window: send to workspace (raw keycodes for layout-independent number keys)
hl.bind("SUPER + SHIFT + code:10", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 1"), { hidden = true })
hl.bind("SUPER + SHIFT + code:11", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 2"), { hidden = true })
hl.bind("SUPER + SHIFT + code:12", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 3"), { hidden = true })
hl.bind("SUPER + SHIFT + code:13", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 4"), { hidden = true })
hl.bind("SUPER + SHIFT + code:14", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 5"), { hidden = true })
hl.bind("SUPER + SHIFT + code:15", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 6"), { hidden = true })
hl.bind("SUPER + SHIFT + code:16", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 7"), { hidden = true })
hl.bind("SUPER + SHIFT + code:17", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 8"), { hidden = true })
hl.bind("SUPER + SHIFT + code:18", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 9"), { hidden = true })
hl.bind("SUPER + SHIFT + code:19", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 10"), { hidden = true })
-- keypad numshift
hl.bind("SUPER + SHIFT + code:87", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 1"), { hidden = true })
hl.bind("SUPER + SHIFT + code:88", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 2"), { hidden = true })
hl.bind("SUPER + SHIFT + code:89", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 3"), { hidden = true })
hl.bind("SUPER + SHIFT + code:83", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 4"), { hidden = true })
hl.bind("SUPER + SHIFT + code:84", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 5"), { hidden = true })
hl.bind("SUPER + SHIFT + code:85", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 6"), { hidden = true })
hl.bind("SUPER + SHIFT + code:79", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 7"), { hidden = true })
hl.bind("SUPER + SHIFT + code:80", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 8"), { hidden = true })
hl.bind("SUPER + SHIFT + code:81", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 9"), { hidden = true })
hl.bind("SUPER + SHIFT + code:90", hl.dsp.exec_cmd("~/.config/hypr/hyprland/scripts/workspace_action.sh movetoworkspacesilent 10"), { hidden = true })

hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:special", follow = false }), { description = "Send to scratchpad" })
